/* tslint:disable */
/* eslint-disable */
/**
 * FlagQuest Backend
 * The API for the FlagQuest guessing game
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface AnswerOption
 */
export interface AnswerOption {
    /**
     * 
     * @type {string}
     * @memberof AnswerOption
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AnswerOption
     */
    isCorrect?: boolean;
}

/**
 * Check if a given object implements the AnswerOption interface.
 */
export function instanceOfAnswerOption(value: object): boolean {
    return true;
}

export function AnswerOptionFromJSON(json: any): AnswerOption {
    return AnswerOptionFromJSONTyped(json, false);
}

export function AnswerOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnswerOption {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'isCorrect': json['isCorrect'] == null ? undefined : json['isCorrect'],
    };
}

export function AnswerOptionToJSON(value?: AnswerOption | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'isCorrect': value['isCorrect'],
    };
}

