/* tslint:disable */
/* eslint-disable */
/**
 * FlagQuest Backend
 * The API for the FlagQuest guessing game
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Nationality = {
    German: 'German',
    Norsk: 'Norsk',
    English: 'English',
    Nederlands: 'Nederlands'
} as const;
export type Nationality = typeof Nationality[keyof typeof Nationality];


export function NationalityFromJSON(json: any): Nationality {
    return NationalityFromJSONTyped(json, false);
}

export function NationalityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Nationality {
    return json as Nationality;
}

export function NationalityToJSON(value?: Nationality | null): any {
    return value as any;
}

