/* tslint:disable */
/* eslint-disable */
/**
 * FlagQuest Backend
 * The API for the FlagQuest guessing game
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Question } from './Question';
import {
    QuestionFromJSON,
    QuestionFromJSONTyped,
    QuestionToJSON,
} from './Question';

/**
 * 
 * @export
 * @interface Quiz
 */
export interface Quiz {
    /**
     * 
     * @type {Array<Question>}
     * @memberof Quiz
     */
    questions?: Array<Question>;
}

/**
 * Check if a given object implements the Quiz interface.
 */
export function instanceOfQuiz(value: object): boolean {
    return true;
}

export function QuizFromJSON(json: any): Quiz {
    return QuizFromJSONTyped(json, false);
}

export function QuizFromJSONTyped(json: any, ignoreDiscriminator: boolean): Quiz {
    if (json == null) {
        return json;
    }
    return {
        
        'questions': json['questions'] == null ? undefined : ((json['questions'] as Array<any>).map(QuestionFromJSON)),
    };
}

export function QuizToJSON(value?: Quiz | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'questions': value['questions'] == null ? undefined : ((value['questions'] as Array<any>).map(QuestionToJSON)),
    };
}

