/* tslint:disable */
/* eslint-disable */
/**
 * FlagQuest Backend
 * The API for the FlagQuest guessing game
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Nationality } from './Nationality';
import {
    NationalityFromJSON,
    NationalityFromJSONTyped,
    NationalityToJSON,
} from './Nationality';

/**
 * 
 * @export
 * @interface RequestUser
 */
export interface RequestUser {
    /**
     * 
     * @type {string}
     * @memberof RequestUser
     */
    userName?: string;
    /**
     * 
     * @type {Nationality}
     * @memberof RequestUser
     */
    nationality?: Nationality;
}

/**
 * Check if a given object implements the RequestUser interface.
 */
export function instanceOfRequestUser(value: object): boolean {
    return true;
}

export function RequestUserFromJSON(json: any): RequestUser {
    return RequestUserFromJSONTyped(json, false);
}

export function RequestUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestUser {
    if (json == null) {
        return json;
    }
    return {
        
        'userName': json['userName'] == null ? undefined : json['userName'],
        'nationality': json['nationality'] == null ? undefined : NationalityFromJSON(json['nationality']),
    };
}

export function RequestUserToJSON(value?: RequestUser | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userName': value['userName'],
        'nationality': NationalityToJSON(value['nationality']),
    };
}

